/* KalkulatorOnline Stage 8 — Admin CMS */
(function(){
  'use strict';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const DRAFT_KEY='ko-cms-draft-v1', AUTH_KEY='ko-cms-auth-v1';
  const CALCS=[
    ['index.html','Kalkulator BMI','Kesehatan'],['kalkulator-kalori.html','Kalkulator Kalori','Kesehatan'],['kalkulator-bmr.html','Kalkulator BMR','Kesehatan'],['kalkulator-air.html','Kalkulator Air Minum','Kesehatan'],['kalkulator-whtr.html','Kalkulator WHtR','Kesehatan'],['kalkulator-body-fat.html','Body Fat %','Kesehatan'],['kalkulator-masa-subur.html','Masa Subur','Kesehatan'],['kalkulator-kehamilan.html','Kalkulator Kehamilan','Kesehatan'],['kalkulator-kontraksi.html','Timer Kontraksi','Kesehatan'],['kalkulator-tendangan.html','Penghitung Tendangan','Kesehatan'],['kalkulator-ukuran-janin.html','Ukuran Janin','Kesehatan'],['kalkulator-cicilan.html','Kalkulator Cicilan','Keuangan'],['kalkulator-diskon.html','Kalkulator Diskon','Keuangan'],['kalkulator-ppn.html','Kalkulator PPN','Keuangan'],['kalkulator-persen.html','Kalkulator Persentase','Keuangan'],['kalkulator-umur.html','Kalkulator Umur','Umum'],['konversi-satuan.html','Konversi Satuan','Umum']
  ].map(x=>({u:x[0],t:x[1],c:x[2]}));
  const clone=v=>JSON.parse(JSON.stringify(v||{}));
  let state=clone(window.KO_CMS_DEFAULTS||{}), faqPage='index.html', dirty=false, toastTimer;

  function toast(msg){const el=$('#cmsToast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
  function markDirty(on=true){dirty=on;$('#unsaved').hidden=!on;}
  function safe(){return window.KOCMS?.sanitize?window.KOCMS.sanitize(state):clone(state)}
  function storeDraft(content){try{localStorage.setItem(DRAFT_KEY,JSON.stringify(content));return true}catch(e){toast('Browser tidak dapat menyimpan draft.');return false}}
  function readDraft(){try{return JSON.parse(localStorage.getItem(DRAFT_KEY)||'null')}catch(e){return null}}
  function currentPane(name){$$('[data-pane-content]').forEach(x=>x.classList.toggle('active',x.dataset.paneContent===name));$$('[data-pane]').forEach(x=>x.classList.toggle('active',x.dataset.pane===name));const b=$(`[data-pane="${name}"]`);$('#cmsTitle').textContent=(b?.textContent||'CMS').trim();$('#cmsSide').classList.remove('open');if(name==='backup')updateJsonPreview();}

  function setText(id,val){const el=$('#'+id);if(el)el.value=val??''}
  function setCheck(id,val){const el=$('#'+id);if(el)el.checked=!!val}
  function populateStatic(){
    const s=state.site||{}, h=state.home||{}, p=state.ppn||{}, sp=state.sponsor||{};
    setCheck('annEnabled',s.announcement?.enabled);setText('annText',s.announcement?.text);setText('annUrl',s.announcement?.url);setText('annCta',s.announcement?.cta);
    setText('homeEyebrow',h.eyebrow);setText('homeTitle',h.title);setText('homeAccent',h.titleAccent);setText('homeDescription',h.description);setText('homeSearch',h.searchPlaceholder);setText('homeDiscovery',h.discoveryTitle);setText('homeFeatured',h.featuredLabel);
    setText('ppnSubtitle',p.subtitle);setText('ppnIntro',p.intro);setText('ppnDefault',p.defaultRate);
    setCheck('sponsorEnabled',sp.enabled);setText('sponsorLabel',sp.label);setText('sponsorCta',sp.cta);setText('sponsorTitle',sp.title);setText('sponsorDescription',sp.description);setText('sponsorUrl',sp.url);
    setText('footerTagline',s.footerTagline);setText('footerStage',s.footerStage);
  }
  function collectStatic(){
    state.site=state.site||{};state.site.announcement={enabled:$('#annEnabled').checked,text:$('#annText').value,url:$('#annUrl').value,cta:$('#annCta').value};state.site.footerTagline=$('#footerTagline').value;state.site.footerStage=$('#footerStage').value;
    state.home=state.home||{};Object.assign(state.home,{eyebrow:$('#homeEyebrow').value,title:$('#homeTitle').value,titleAccent:$('#homeAccent').value,description:$('#homeDescription').value,searchPlaceholder:$('#homeSearch').value,discoveryTitle:$('#homeDiscovery').value,featuredLabel:$('#homeFeatured').value});
    state.ppn=state.ppn||{};Object.assign(state.ppn,{subtitle:$('#ppnSubtitle').value,intro:$('#ppnIntro').value,defaultRate:Number($('#ppnDefault').value)});
    state.sponsor={enabled:$('#sponsorEnabled').checked,label:$('#sponsorLabel').value,title:$('#sponsorTitle').value,description:$('#sponsorDescription').value,url:$('#sponsorUrl').value,cta:$('#sponsorCta').value};
  }
  function renderHighlights(){const box=$('#highlightList'), list=state.home?.highlights||[];box.innerHTML=list.map((x,i)=>`<div class="cms-repeat-item" data-highlight-row="${i}"><div class="cms-repeat-head"><strong>Kartu ${i+1}</strong><button type="button" class="cms-icon-btn danger" data-remove-highlight="${i}" aria-label="Hapus"><i data-lucide="trash-2"></i></button></div><label class="cms-check"><input data-h="enabled" type="checkbox" ${x.enabled?'checked':''}> Aktif</label><div class="cms-row"><div class="cms-field"><span>Label</span><input data-h="label" value="${escAttr(x.label)}"></div><div class="cms-field"><span>Icon Lucide</span><input data-h="icon" value="${escAttr(x.icon||'sparkles')}"></div></div><div class="cms-field"><span>Judul</span><input data-h="title" value="${escAttr(x.title)}"></div><div class="cms-field"><span>Deskripsi</span><textarea data-h="description">${escHtml(x.description)}</textarea></div><div class="cms-field"><span>URL</span><input data-h="url" value="${escAttr(x.url)}"></div></div>`).join('');window.lucide?.createIcons();}
  function syncHighlights(){state.home=state.home||{};state.home.highlights=$$('[data-highlight-row]').map(row=>({enabled:$('[data-h="enabled"]',row).checked,label:$('[data-h="label"]',row).value,icon:$('[data-h="icon"]',row).value,title:$('[data-h="title"]',row).value,description:$('[data-h="description"]',row).value,url:$('[data-h="url"]',row).value}));}
  function renderPopular(){const selected=new Set(state.popular?.curated||[]);$('#popularChecks').innerHTML=CALCS.map(c=>`<label class="cms-check-card"><input type="checkbox" data-popular="${c.u}" ${selected.has(c.u)?'checked':''}><span><b>${escHtml(c.t)}</b><br><small>${c.c}</small></span></label>`).join('');}
  function syncPopular(){const vals=$$('[data-popular]:checked').map(x=>x.dataset.popular).slice(0,12);state.popular={curated:vals};}
  function renderFaqSelect(){const sel=$('#faqPage');sel.innerHTML=CALCS.map(c=>`<option value="${c.u}">${escHtml(c.t)}</option>`).join('');sel.value=faqPage;}
  function renderFaq(){const list=state.faqOverrides?.[faqPage]||[];$('#faqList').innerHTML=list.length?list.map((x,i)=>`<div class="cms-repeat-item" data-faq-row="${i}"><div class="cms-repeat-head"><strong>Pertanyaan ${i+1}</strong><button type="button" class="cms-icon-btn danger" data-remove-faq="${i}"><i data-lucide="trash-2"></i></button></div><div class="cms-field"><span>Pertanyaan</span><input data-faq="q" maxlength="180" value="${escAttr(x.q||x.question||'')}"></div><div class="cms-field"><span>Jawaban</span><textarea data-faq="a" maxlength="700">${escHtml(x.a||x.answer||'')}</textarea></div></div>`).join(''):`<div class="cms-status warn"><i></i><span>Belum ada override. Halaman memakai FAQ bawaan Stage 7.</span></div>`;window.lucide?.createIcons();renderContext();}
  function syncFaq(){state.faqOverrides=state.faqOverrides||{};const rows=$$('[data-faq-row]');if(!rows.length){if(state.faqOverrides[faqPage]?.length===0)delete state.faqOverrides[faqPage];return;}const arr=rows.map(r=>({q:$('[data-faq="q"]',r).value,a:$('[data-faq="a"]',r).value})).filter(x=>x.q.trim()&&x.a.trim());if(arr.length)state.faqOverrides[faqPage]=arr;else delete state.faqOverrides[faqPage];}
  function renderContext(){const selected=new Set(state.contextLinks?.[faqPage]||[]);$('#contextChecks').innerHTML=CALCS.filter(c=>c.u!==faqPage).map(c=>`<label class="cms-check-card"><input type="checkbox" data-context="${c.u}" ${selected.has(c.u)?'checked':''}><span>${escHtml(c.t)}</span></label>`).join('');}
  function syncContext(){state.contextLinks=state.contextLinks||{};const vals=$$('[data-context]:checked').map(x=>x.dataset.context).slice(0,6);if(vals.length)state.contextLinks[faqPage]=vals;else delete state.contextLinks[faqPage];}
  function renderRates(){const list=state.ppn?.rates||[];$('#ppnRates').innerHTML=list.map((x,i)=>`<div class="cms-repeat-item" data-rate-row="${i}"><div class="cms-repeat-head"><strong>Tarif ${i+1}</strong><button type="button" class="cms-icon-btn danger" data-remove-rate="${i}"><i data-lucide="trash-2"></i></button></div><div class="cms-row"><div class="cms-field"><span>Nilai (%)</span><input data-rate="value" type="number" min="0" max="100" step="0.01" value="${Number(x.value)||0}"></div><div class="cms-field"><span>Label</span><input data-rate="label" value="${escAttr(x.label||'')}"></div></div></div>`).join('');window.lucide?.createIcons();}
  function syncRates(){state.ppn=state.ppn||{};state.ppn.rates=$$('[data-rate-row]').map(r=>({value:Number($('[data-rate="value"]',r).value),label:$('[data-rate="label"]',r).value})).filter(x=>Number.isFinite(x.value));}
  function collect(){collectStatic();syncHighlights();syncPopular();syncFaq();syncContext();syncRates();state=window.KOCMS?.sanitize?window.KOCMS.sanitize(state):state;return state;}
  function populate(all){state=window.KOCMS?.sanitize?window.KOCMS.sanitize(all):clone(all);populateStatic();renderHighlights();renderPopular();renderFaqSelect();renderFaq();renderRates();updateJsonPreview();markDirty(false);}
  function escHtml(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function escAttr(v){return escHtml(v).replace(/`/g,'&#96;')}
  function updateJsonPreview(){try{$('#jsonPreview').textContent=JSON.stringify(collect(),null,2)}catch(e){}}

  function configReady(){const f=window.KO_CMS_CONFIG?.firebase||{};return !!(window.KO_CMS_CONFIG?.enabled&&f.apiKey&&f.projectId&&f.documentPath)}
  function endpoint(){const f=window.KO_CMS_CONFIG.firebase;const path=String(f.documentPath).split('/').filter(Boolean).map(encodeURIComponent).join('/');const base=`https://firestore.googleapis.com/v1/projects/${encodeURIComponent(f.projectId)}/databases/(default)/documents/${path}`;return f.apiKey?`${base}?key=${encodeURIComponent(f.apiKey)}`:base}
  function authRead(){try{return JSON.parse(sessionStorage.getItem(AUTH_KEY)||'null')}catch(e){return null}}
  function authWrite(v){try{v?sessionStorage.setItem(AUTH_KEY,JSON.stringify(v)):sessionStorage.removeItem(AUTH_KEY)}catch(e){}}
  function validAuth(){const a=authRead();return a?.idToken&&Number(a.expiresAt)>Date.now();}
  function renderCloud(){
    const cfg=window.KO_CMS_CONFIG||{}, f=cfg.firebase||{}, ready=configReady();
    const c=$('#cloudStatus'),d=$('#cloudConfigDetail');[c,d].forEach(el=>{el.className='cms-status '+(ready?'good':'warn');el.innerHTML=`<i></i><span>${ready?'Firebase CMS siap digunakan':'Cloud CMS belum dikonfigurasi'}</span>`});
    $('#cloudConfigCode').textContent=`enabled: ${!!cfg.enabled}\nprojectId: ${f.projectId||'(kosong)'}\ndocumentPath: ${f.documentPath||'(kosong)'}\napiKey: ${f.apiKey?f.apiKey.slice(0,6)+'••••••••':'(kosong)'}`;
    const a=authRead(), logged=validAuth();$('#authLoggedOut').hidden=logged;$('#authLoggedIn').hidden=!logged;if(logged)$('#authEmail').textContent=a.email||'Admin';
    $('#publishTop').disabled=!ready||!logged;$('#publishBtn').disabled=!ready||!logged;$('#loadPublished').disabled=!ready;
    $('#publishHint').textContent=!ready?'Isi cms-config.js dan deploy Firestore rules terlebih dahulu.':!logged?'Login admin untuk mengaktifkan Publish.':'Siap publish. Firestore Security Rules tetap menjadi lapisan otorisasi utama.';
  }
  async function signIn(){
    if(!configReady()){toast('Konfigurasi Firebase belum lengkap.');return}const email=$('#adminEmail').value.trim(),password=$('#adminPassword').value;if(!email||!password){toast('Isi email dan password admin.');return}
    const b=$('#loginBtn');b.disabled=true;b.textContent='Login…';try{const key=window.KO_CMS_CONFIG.firebase.apiKey;const res=await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=${encodeURIComponent(key)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,returnSecureToken:true})});const data=await res.json();if(!res.ok)throw new Error(data?.error?.message||'LOGIN_FAILED');authWrite({idToken:data.idToken,email:data.email||email,expiresAt:Date.now()+Math.max(60,Number(data.expiresIn)||3600)*1000-60000});$('#adminPassword').value='';renderCloud();toast('Login admin berhasil.')}catch(e){toast('Login gagal: '+String(e.message||e).replace(/_/g,' ').slice(0,90))}finally{b.disabled=false;b.innerHTML='<i data-lucide="log-in"></i> Login';window.lucide?.createIcons();}}
  async function loadPublished(){if(!configReady())return;const b=$('#loadPublished');b.disabled=true;try{const res=await fetch(endpoint(),{headers:{Accept:'application/json'},cache:'no-store'});if(res.status===404){toast('Dokumen CMS belum pernah dipublish.');return}const doc=await res.json();if(!res.ok)throw new Error(doc?.error?.message||`HTTP ${res.status}`);const raw=doc?.fields?.payload?.stringValue;if(!raw)throw new Error('Payload CMS kosong');populate(JSON.parse(raw));storeDraft(state);$('#sourceStatus').className='cms-status good';$('#sourceStatus').innerHTML='<i></i><span>Published Firestore dimuat</span>';toast('Konten published berhasil dimuat.')}catch(e){toast('Gagal memuat: '+String(e.message||e).slice(0,100))}finally{b.disabled=false}}
  async function publish(){
    if(!configReady()){toast('Firebase CMS belum dikonfigurasi.');return}const auth=authRead();if(!validAuth()){authWrite(null);renderCloud();toast('Session login habis. Login kembali.');return}const content=collect();
    const buttons=[$('#publishTop'),$('#publishBtn')];buttons.forEach(b=>b.disabled=true);try{const res=await fetch(endpoint(),{method:'PATCH',headers:{'Content-Type':'application/json','Authorization':`Bearer ${auth.idToken}`},body:JSON.stringify({fields:{payload:{stringValue:JSON.stringify(content)},schemaVersion:{integerValue:'1'},updatedAt:{timestampValue:new Date().toISOString()}}})});const data=await res.json();if(!res.ok)throw new Error(data?.error?.message||`HTTP ${res.status}`);storeDraft(content);try{const f=window.KO_CMS_CONFIG.firebase;localStorage.setItem('ko-cms-public-cache-v1',JSON.stringify({scope:`${f.projectId||''}|${f.documentPath||''}`,at:Date.now(),content}))}catch(e){}markDirty(false);$('#sourceStatus').className='cms-status good';$('#sourceStatus').innerHTML='<i></i><span>Published ke Firestore</span>';$('#sourceHint').textContent=`Terakhir publish: ${new Date().toLocaleString('id-ID')}`;toast('Publish berhasil. Konten publik akan memakai versi baru.')}catch(e){toast('Publish gagal: '+String(e.message||e).slice(0,120))}finally{renderCloud();buttons.forEach(b=>b.disabled=!validAuth()||!configReady())}}
  function saveDraft(){const content=collect();if(storeDraft(content)){markDirty(false);$('#sourceStatus').className='cms-status good';$('#sourceStatus').innerHTML='<i></i><span>Draft lokal tersimpan</span>';$('#sourceHint').textContent='Draft hanya tersimpan pada browser ini sampai dipublish.';toast('Draft tersimpan.')}}
  function preview(){saveDraft();try{sessionStorage.setItem('ko-cms-preview-active','1')}catch(e){}window.open('index.html?cmsPreview=1','_blank','noopener');}
  function exportJson(){const content=collect(),blob=new Blob([JSON.stringify(content,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`kalkulatoronline-cms-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Backup JSON dibuat.');}
  async function importJson(file){try{const raw=await file.text(),data=JSON.parse(raw);populate(data);markDirty(true);toast('JSON berhasil diimport. Periksa lalu simpan/publish.')}catch(e){toast('File JSON tidak valid.')}}

  document.addEventListener('click',e=>{
    const nav=e.target.closest('[data-pane]');if(nav){currentPane(nav.dataset.pane);return}
    const rh=e.target.closest('[data-remove-highlight]');if(rh){syncHighlights();state.home.highlights.splice(Number(rh.dataset.removeHighlight),1);renderHighlights();markDirty();return}
    const rf=e.target.closest('[data-remove-faq]');if(rf){syncFaq();state.faqOverrides[faqPage]?.splice(Number(rf.dataset.removeFaq),1);if(!state.faqOverrides[faqPage]?.length)delete state.faqOverrides[faqPage];renderFaq();markDirty();return}
    const rr=e.target.closest('[data-remove-rate]');if(rr){syncRates();state.ppn.rates.splice(Number(rr.dataset.removeRate),1);renderRates();markDirty();return}
  });
  $('#addHighlight').addEventListener('click',()=>{syncHighlights();state.home.highlights=state.home.highlights||[];if(state.home.highlights.length>=6){toast('Maksimal 6 kartu.');return}state.home.highlights.push({enabled:true,label:'INFO',title:'Judul baru',description:'Deskripsi singkat',url:'index.html',icon:'sparkles'});renderHighlights();markDirty()});
  $('#addFaq').addEventListener('click',()=>{syncFaq();state.faqOverrides=state.faqOverrides||{};state.faqOverrides[faqPage]=state.faqOverrides[faqPage]||[];if(state.faqOverrides[faqPage].length>=10){toast('Maksimal 10 FAQ per halaman.');return}state.faqOverrides[faqPage].push({q:'Pertanyaan baru?',a:'Tulis jawaban di sini.'});renderFaq();markDirty()});
  $('#clearFaq').addEventListener('click',()=>{state.faqOverrides=state.faqOverrides||{};delete state.faqOverrides[faqPage];renderFaq();markDirty();toast('FAQ halaman kembali memakai bawaan.')});
  $('#addRate').addEventListener('click',()=>{syncRates();state.ppn.rates=state.ppn.rates||[];if(state.ppn.rates.length>=12){toast('Maksimal 12 tarif.');return}state.ppn.rates.push({value:0,label:'Tarif baru'});renderRates();markDirty()});
  $('#faqPage').addEventListener('change',e=>{syncFaq();syncContext();faqPage=e.target.value;renderFaq();markDirty()});
  $('#popularChecks').addEventListener('change',e=>{if(e.target.matches('[data-popular]')&&$$('[data-popular]:checked').length>12){e.target.checked=false;toast('Maksimal 12 kalkulator.')}markDirty()});
  $('#contextChecks').addEventListener('change',e=>{if(e.target.matches('[data-context]')&&$$('[data-context]:checked').length>6){e.target.checked=false;toast('Maksimal 6 rekomendasi.')}markDirty()});
  $('.cms-content').addEventListener('input',e=>{if(e.target.matches('input,textarea,select'))markDirty()});$('.cms-content').addEventListener('change',e=>{if(e.target.matches('input,textarea,select'))markDirty()});
  $('#saveDraft').addEventListener('click',saveDraft);$('#previewBtn').addEventListener('click',preview);$('#publishTop').addEventListener('click',publish);$('#publishBtn').addEventListener('click',publish);$('#loadPublished').addEventListener('click',loadPublished);$('#loginBtn').addEventListener('click',signIn);$('#logoutBtn').addEventListener('click',()=>{authWrite(null);renderCloud();toast('Logout berhasil.')});
  $('#exportJson').addEventListener('click',exportJson);$('#importJson').addEventListener('change',e=>{const f=e.target.files?.[0];if(f)importJson(f);e.target.value=''});$('#resetDefaults').addEventListener('click',()=>{if(confirm('Reset editor ke konten bawaan? Published Firestore tidak berubah sampai Publish.')){populate(window.KO_CMS_DEFAULTS);markDirty(true);toast('Editor dikembalikan ke default.')}});$('#cmsMenu').addEventListener('click',()=>$('#cmsSide').classList.toggle('open'));
  document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();saveDraft()}if(e.key==='Escape')$('#cmsSide').classList.remove('open')});

  async function init(){
    const mode=localStorage.getItem('ko-theme')||'auto';const dark=mode==='dark'||(mode==='auto'&&matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.setAttribute('data-theme',dark?'dark':'light');
    try{if(window.KOCMS?.ready)await window.KOCMS.ready}catch(e){}
    const draft=readDraft();populate(draft||window.KOCMS?.content||window.KO_CMS_DEFAULTS);
    $('#sourceStatus').className='cms-status '+(draft?'good':'warn');$('#sourceStatus').innerHTML=`<i></i><span>${draft?'Draft lokal tersedia':`Sumber saat ini: ${window.KOCMS?.source||'bundled'}`}</span>`;$('#sourceHint').textContent=draft?'Draft lokal diprioritaskan di editor. Gunakan Muat Published untuk mengambil cloud.':'Belum ada draft lokal.';
    renderCloud();window.lucide?.createIcons();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
